# Generated by Django 5.0.6 on 2024-05-21 05:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bolim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('rasm', models.ImageField(upload_to='bolimlar/')),
            ],
        ),
        migrations.CreateModel(
            name='IchkiBolim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('rasm', models.ImageField(upload_to='ichki-bolimlar/')),
                ('bolim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.bolim')),
            ],
        ),
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('batafsil', models.TextField(blank=True, null=True)),
                ('narx', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('chegirma', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('kafolat', models.CharField(blank=True, max_length=50, null=True)),
                ('yetkazish', models.CharField(blank=True, max_length=50, null=True)),
                ('mavjud', models.BooleanField(default=True)),
                ('baho', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('davlat', models.CharField(blank=True, max_length=50, null=True)),
                ('korish', models.PositiveSmallIntegerField(default=0)),
                ('buyurtma_soni', models.PositiveIntegerField(default=0)),
                ('ichki_bolim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.ichkibolim')),
            ],
        ),
        migrations.CreateModel(
            name='Rasm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='mahsulotlar/')),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.mahsulot')),
            ],
        ),
        migrations.CreateModel(
            name='Xususiyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('qiymat', models.CharField(max_length=40)),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.mahsulot')),
            ],
        ),
    ]
