# Generated by Django 5.0.6 on 2024-05-16 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_ichkibolim_bolim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ichkibolim',
            name='bolim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.bolim'),
        ),
    ]
