# Generated by Django 5.0.6 on 2024-05-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_alter_baholash_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='baholash',
            name='sana',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01'),
            preserve_default=False,
        ),
    ]
