# Generated by Django 5.0.6 on 2024-05-21 06:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_baholash_sana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahsulot',
            name='baho',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
