# Generated by Django 5.0.6 on 2024-05-21 06:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_alter_mahsulot_baho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahsulot',
            name='baho',
            field=models.FloatField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
